@tool
class_name StrudelControlsTable
extends RefCounted

## Таблица управляющих функций Strudel — ПОРОЖДЕНА, не написана руками.
##
## Источник: packages/core/controls.mjs Булки, генератор tools/gen_controls.py.
## Править надо генератор, а не этот файл: список меняется вместе с
## апстримом, и ручная копия разъезжается молча. Записей: 331.
##
## Значение записи — список имён. У составных функций их несколько:
## s("bd:3:0.7") раскладывается по ["s", "n", "gain"] — имя, индекс
## сэмпла и громкость через двоеточие.

const CONTROLS := {
	"s": {"names": ["s", "n", "gain"], "aliases": ["sound"]},
	"wt": {"names": ["wt"], "aliases": ["wavetablePosition"]},
	"wtenv": {"names": ["wtenv"], "aliases": []},
	"wtattack": {"names": ["wtattack"], "aliases": ["wtatt"]},
	"wtdecay": {"names": ["wtdecay"], "aliases": ["wtdec"]},
	"wtsustain": {"names": ["wtsustain"], "aliases": ["wtsus"]},
	"wtrelease": {"names": ["wtrelease"], "aliases": ["wtrel"]},
	"wtrate": {"names": ["wtrate"], "aliases": []},
	"wtsync": {"names": ["wtsync"], "aliases": []},
	"wtdepth": {"names": ["wtdepth"], "aliases": []},
	"wtshape": {"names": ["wtshape"], "aliases": []},
	"wtdc": {"names": ["wtdc"], "aliases": []},
	"wtskew": {"names": ["wtskew"], "aliases": []},
	"warp": {"names": ["warp"], "aliases": ["wavetableWarp"]},
	"warpattack": {"names": ["warpattack"], "aliases": ["warpatt"]},
	"warpdecay": {"names": ["warpdecay"], "aliases": ["warpdec"]},
	"warpsustain": {"names": ["warpsustain"], "aliases": ["warpsus"]},
	"warprelease": {"names": ["warprelease"], "aliases": ["warprel"]},
	"warprate": {"names": ["warprate"], "aliases": []},
	"warpdepth": {"names": ["warpdepth"], "aliases": []},
	"warpshape": {"names": ["warpshape"], "aliases": []},
	"warpdc": {"names": ["warpdc"], "aliases": []},
	"warpskew": {"names": ["warpskew"], "aliases": []},
	"warpmode": {"names": ["warpmode"], "aliases": ["wavetableWarpMode"]},
	"wtphaserand": {"names": ["wtphaserand"], "aliases": ["wavetablePhaseRand"]},
	"warpenv": {"names": ["warpenv"], "aliases": []},
	"warpsync": {"names": ["warpsync"], "aliases": []},
	"source": {"names": ["source"], "aliases": ["src"]},
	"n": {"names": ["n"], "aliases": []},
	"i": {"names": ["i"], "aliases": []},
	"note": {"names": ["note", "n"], "aliases": []},
	"accelerate": {"names": ["accelerate"], "aliases": []},
	"velocity": {"names": ["velocity"], "aliases": ["vel"]},
	"gain": {"names": ["gain"], "aliases": []},
	"postgain": {"names": ["postgain"], "aliases": []},
	"amp": {"names": ["amp"], "aliases": []},
	"bank": {"names": ["bank"], "aliases": []},
	"chorus": {"names": ["chorus"], "aliases": []},
	"analyze": {"names": ["analyze"], "aliases": []},
	"fft": {"names": ["fft"], "aliases": []},
	"attack": {"names": ["attack"], "aliases": ["att"]},
	"decay": {"names": ["decay"], "aliases": ["dec"]},
	"sustain": {"names": ["sustain"], "aliases": ["sus"]},
	"release": {"names": ["release"], "aliases": ["rel"]},
	"hold": {"names": ["hold"], "aliases": []},
	"bandf": {"names": ["bandf", "bandq", "bpenv"], "aliases": ["bpf", "bp"]},
	"bandq": {"names": ["bandq"], "aliases": ["bpq"]},
	"begin": {"names": ["begin"], "aliases": []},
	"end": {"names": ["end"], "aliases": []},
	"loop": {"names": ["loop"], "aliases": []},
	"loopBegin": {"names": ["loopBegin"], "aliases": ["loopb"]},
	"loopEnd": {"names": ["loopEnd"], "aliases": ["loope"]},
	"crush": {"names": ["crush"], "aliases": []},
	"coarse": {"names": ["coarse"], "aliases": []},
	"tremolo": {"names": ["tremolo", "tremolodepth", "tremoloskew", "tremolophase"], "aliases": ["trem"]},
	"tremolosync": {"names": ["tremolosync", "tremolodepth", "tremoloskew", "tremolophase"], "aliases": ["tremsync"]},
	"tremolodepth": {"names": ["tremolodepth"], "aliases": ["tremdepth"]},
	"tremoloskew": {"names": ["tremoloskew"], "aliases": ["tremskew"]},
	"tremolophase": {"names": ["tremolophase"], "aliases": ["tremphase"]},
	"tremoloshape": {"names": ["tremoloshape"], "aliases": ["tremshape"]},
	"drive": {"names": ["drive"], "aliases": []},
	"duckorbit": {"names": ["duckorbit"], "aliases": ["duck"]},
	"duckdepth": {"names": ["duckdepth"], "aliases": []},
	"duckonset": {"names": ["duckonset"], "aliases": ["duckons"]},
	"duckattack": {"names": ["duckattack"], "aliases": ["duckatt", "datt"]},
	"byteBeatExpression": {"names": ["byteBeatExpression"], "aliases": ["bbexpr", "bb"]},
	"byteBeatStartTime": {"names": ["byteBeatStartTime"], "aliases": ["bbst"]},
	"channels": {"names": ["channels"], "aliases": ["ch"]},
	"pw": {"names": ["pw", "pwrate", "pwsweep"], "aliases": []},
	"pwrate": {"names": ["pwrate"], "aliases": ["pwr"]},
	"pwsweep": {"names": ["pwsweep"], "aliases": ["pws"]},
	"phaserrate": {"names": ["phaserrate", "phaserdepth", "phasercenter", "phasersweep"], "aliases": ["ph", "phaser"]},
	"phasersweep": {"names": ["phasersweep"], "aliases": ["phs"]},
	"phasercenter": {"names": ["phasercenter"], "aliases": ["phc"]},
	"phaserdepth": {"names": ["phaserdepth"], "aliases": ["phd", "phasdp"]},
	"channel": {"names": ["channel"], "aliases": []},
	"cut": {"names": ["cut"], "aliases": []},
	"cutoff": {"names": ["cutoff", "resonance", "lpenv"], "aliases": ["ctf", "lpf", "lp"]},
	"lpenv": {"names": ["lpenv"], "aliases": ["lpe"]},
	"hpenv": {"names": ["hpenv"], "aliases": ["hpe"]},
	"bpenv": {"names": ["bpenv"], "aliases": ["bpe"]},
	"lpattack": {"names": ["lpattack"], "aliases": ["lpa"]},
	"hpattack": {"names": ["hpattack"], "aliases": ["hpa"]},
	"bpattack": {"names": ["bpattack"], "aliases": ["bpa"]},
	"lpdecay": {"names": ["lpdecay"], "aliases": ["lpd"]},
	"hpdecay": {"names": ["hpdecay"], "aliases": ["hpd"]},
	"bpdecay": {"names": ["bpdecay"], "aliases": ["bpd"]},
	"lpsustain": {"names": ["lpsustain"], "aliases": ["lps"]},
	"hpsustain": {"names": ["hpsustain"], "aliases": ["hps"]},
	"bpsustain": {"names": ["bpsustain"], "aliases": ["bps"]},
	"lprelease": {"names": ["lprelease"], "aliases": ["lpr"]},
	"hprelease": {"names": ["hprelease"], "aliases": ["hpr"]},
	"bprelease": {"names": ["bprelease"], "aliases": ["bpr"]},
	"ftype": {"names": ["ftype"], "aliases": []},
	"fanchor": {"names": ["fanchor"], "aliases": []},
	"lprate": {"names": ["lprate"], "aliases": []},
	"lpsync": {"names": ["lpsync"], "aliases": []},
	"lpdepth": {"names": ["lpdepth"], "aliases": []},
	"lpdepthfrequency": {"names": ["lpdepthfrequency"], "aliases": ["lpdepthfreq"]},
	"lpshape": {"names": ["lpshape"], "aliases": []},
	"lpdc": {"names": ["lpdc"], "aliases": []},
	"lpskew": {"names": ["lpskew"], "aliases": []},
	"bprate": {"names": ["bprate"], "aliases": []},
	"bpsync": {"names": ["bpsync"], "aliases": []},
	"bpdepth": {"names": ["bpdepth"], "aliases": []},
	"bpdepthfrequency": {"names": ["bpdepthfrequency"], "aliases": ["bpdepthfreq"]},
	"bpshape": {"names": ["bpshape"], "aliases": []},
	"bpdc": {"names": ["bpdc"], "aliases": []},
	"bpskew": {"names": ["bpskew"], "aliases": []},
	"hprate": {"names": ["hprate"], "aliases": []},
	"hpsync": {"names": ["hpsync"], "aliases": []},
	"hpdepth": {"names": ["hpdepth"], "aliases": []},
	"hpdepthfrequency": {"names": ["hpdepthfrequency"], "aliases": ["hpdepthfreq"]},
	"hpshape": {"names": ["hpshape"], "aliases": []},
	"hpdc": {"names": ["hpdc"], "aliases": []},
	"hpskew": {"names": ["hpskew"], "aliases": []},
	"vib": {"names": ["vib", "vibmod"], "aliases": ["vibrato", "v"]},
	"noise": {"names": ["noise"], "aliases": []},
	"vibmod": {"names": ["vibmod", "vib"], "aliases": ["vmod"]},
	"hcutoff": {"names": ["hcutoff", "hresonance", "hpenv"], "aliases": ["hpf", "hp"]},
	"hresonance": {"names": ["hresonance"], "aliases": ["hpq"]},
	"resonance": {"names": ["resonance"], "aliases": ["lpq"]},
	"djf": {"names": ["djf"], "aliases": []},
	"delay": {"names": ["delay", "delaytime", "delayfeedback"], "aliases": []},
	"delayfeedback": {"names": ["delayfeedback"], "aliases": ["delayfb", "dfb"]},
	"delayspeed": {"names": ["delayspeed"], "aliases": []},
	"delaytime": {"names": ["delaytime"], "aliases": ["delayt", "dt"]},
	"delaysync": {"names": ["delaysync"], "aliases": ["delays", "ds"]},
	"lock": {"names": ["lock"], "aliases": []},
	"detune": {"names": ["detune"], "aliases": ["det"]},
	"unison": {"names": ["unison"], "aliases": []},
	"spread": {"names": ["spread"], "aliases": []},
	"dry": {"names": ["dry"], "aliases": []},
	"fadeTime": {"names": ["fadeTime"], "aliases": ["fadeOutTime"]},
	"fadeInTime": {"names": ["fadeInTime"], "aliases": []},
	"freq": {"names": ["freq"], "aliases": []},
	"pattack": {"names": ["pattack"], "aliases": ["patt"]},
	"pdecay": {"names": ["pdecay"], "aliases": ["pdec"]},
	"psustain": {"names": ["psustain"], "aliases": ["psus"]},
	"prelease": {"names": ["prelease"], "aliases": ["prel"]},
	"penv": {"names": ["penv"], "aliases": []},
	"pcurve": {"names": ["pcurve"], "aliases": []},
	"panchor": {"names": ["panchor"], "aliases": []},
	"gate": {"names": ["gate"], "aliases": ["gat"]},
	"leslie": {"names": ["leslie"], "aliases": []},
	"lrate": {"names": ["lrate"], "aliases": []},
	"lsize": {"names": ["lsize"], "aliases": []},
	"activeLabel": {"names": ["activeLabel"], "aliases": []},
	"label": {"names": ["label", "activeLabel"], "aliases": []},
	"degree": {"names": ["degree"], "aliases": []},
	"mtranspose": {"names": ["mtranspose"], "aliases": []},
	"ctranspose": {"names": ["ctranspose"], "aliases": []},
	"harmonic": {"names": ["harmonic"], "aliases": []},
	"stepsPerOctave": {"names": ["stepsPerOctave"], "aliases": []},
	"octaveR": {"names": ["octaveR"], "aliases": []},
	"nudge": {"names": ["nudge"], "aliases": []},
	"octave": {"names": ["octave"], "aliases": ["oct"]},
	"orbit": {"names": ["orbit"], "aliases": ["o"]},
	"bus": {"names": ["bus"], "aliases": []},
	"busgain": {"names": ["busgain"], "aliases": ["bgain"]},
	"overgain": {"names": ["overgain"], "aliases": []},
	"overshape": {"names": ["overshape"], "aliases": []},
	"pan": {"names": ["pan"], "aliases": []},
	"panspan": {"names": ["panspan"], "aliases": []},
	"pansplay": {"names": ["pansplay"], "aliases": []},
	"panwidth": {"names": ["panwidth"], "aliases": []},
	"panorient": {"names": ["panorient"], "aliases": []},
	"slide": {"names": ["slide"], "aliases": []},
	"semitone": {"names": ["semitone"], "aliases": []},
	"voice": {"names": ["voice"], "aliases": []},
	"chord": {"names": ["chord"], "aliases": []},
	"dictionary": {"names": ["dictionary"], "aliases": ["dict"]},
	"anchor": {"names": ["anchor"], "aliases": []},
	"offset": {"names": ["offset"], "aliases": []},
	"octaves": {"names": ["octaves"], "aliases": []},
	"mode": {"names": ["mode", "anchor"], "aliases": []},
	"room": {"names": ["room", "size"], "aliases": []},
	"roomlp": {"names": ["roomlp"], "aliases": ["rlp"]},
	"roomdim": {"names": ["roomdim"], "aliases": ["rdim"]},
	"roomfade": {"names": ["roomfade"], "aliases": ["rfade"]},
	"ir": {"names": ["ir", "i"], "aliases": ["iresponse"]},
	"irspeed": {"names": ["irspeed"], "aliases": []},
	"irbegin": {"names": ["irbegin"], "aliases": []},
	"roomsize": {"names": ["roomsize"], "aliases": ["size", "sz", "rsize"]},
	"shape": {"names": ["shape", "shapevol"], "aliases": []},
	"distort": {"names": ["distort", "distortvol", "distorttype"], "aliases": ["dist"]},
	"distortvol": {"names": ["distortvol"], "aliases": ["distvol"]},
	"distorttype": {"names": ["distorttype"], "aliases": ["disttype"]},
	"compressor": {"names": ["compressor", "compressorRatio", "compressorKnee", "compressorAttack", "compressorRelease"], "aliases": []},
	"compressorKnee": {"names": ["compressorKnee"], "aliases": []},
	"compressorRatio": {"names": ["compressorRatio"], "aliases": []},
	"compressorAttack": {"names": ["compressorAttack"], "aliases": []},
	"compressorRelease": {"names": ["compressorRelease"], "aliases": []},
	"speed": {"names": ["speed"], "aliases": []},
	"stretch": {"names": ["stretch"], "aliases": []},
	"unit": {"names": ["unit"], "aliases": []},
	"squiz": {"names": ["squiz"], "aliases": []},
	"vowel": {"names": ["vowel"], "aliases": []},
	"waveloss": {"names": ["waveloss"], "aliases": []},
	"density": {"names": ["density"], "aliases": []},
	"expression": {"names": ["expression"], "aliases": []},
	"sustainpedal": {"names": ["sustainpedal"], "aliases": []},
	"fshift": {"names": ["fshift"], "aliases": []},
	"fshiftnote": {"names": ["fshiftnote"], "aliases": []},
	"fshiftphase": {"names": ["fshiftphase"], "aliases": []},
	"triode": {"names": ["triode"], "aliases": []},
	"krush": {"names": ["krush"], "aliases": []},
	"kcutoff": {"names": ["kcutoff"], "aliases": []},
	"octer": {"names": ["octer"], "aliases": []},
	"octersub": {"names": ["octersub"], "aliases": []},
	"octersubsub": {"names": ["octersubsub"], "aliases": []},
	"ring": {"names": ["ring"], "aliases": []},
	"ringf": {"names": ["ringf"], "aliases": []},
	"ringdf": {"names": ["ringdf"], "aliases": []},
	"freeze": {"names": ["freeze"], "aliases": []},
	"xsdelay": {"names": ["xsdelay"], "aliases": []},
	"tsdelay": {"names": ["tsdelay"], "aliases": []},
	"real": {"names": ["real"], "aliases": []},
	"imag": {"names": ["imag"], "aliases": []},
	"enhance": {"names": ["enhance"], "aliases": []},
	"comb": {"names": ["comb"], "aliases": []},
	"smear": {"names": ["smear"], "aliases": []},
	"scram": {"names": ["scram"], "aliases": []},
	"binshift": {"names": ["binshift"], "aliases": []},
	"hbrick": {"names": ["hbrick"], "aliases": []},
	"lbrick": {"names": ["lbrick"], "aliases": []},
	"frameRate": {"names": ["frameRate"], "aliases": []},
	"frames": {"names": ["frames"], "aliases": []},
	"hours": {"names": ["hours"], "aliases": []},
	"minutes": {"names": ["minutes"], "aliases": []},
	"seconds": {"names": ["seconds"], "aliases": []},
	"songPtr": {"names": ["songPtr"], "aliases": []},
	"uid": {"names": ["uid"], "aliases": []},
	"val": {"names": ["val"], "aliases": []},
	"cps": {"names": ["cps"], "aliases": []},
	"clip": {"names": ["clip"], "aliases": ["legato"]},
	"duration": {"names": ["duration"], "aliases": ["dur"]},
	"zrand": {"names": ["zrand"], "aliases": []},
	"curve": {"names": ["curve"], "aliases": []},
	"deltaSlide": {"names": ["deltaSlide"], "aliases": []},
	"pitchJump": {"names": ["pitchJump"], "aliases": []},
	"pitchJumpTime": {"names": ["pitchJumpTime"], "aliases": []},
	"znoise": {"names": ["znoise"], "aliases": []},
	"zmod": {"names": ["zmod"], "aliases": []},
	"zcrush": {"names": ["zcrush"], "aliases": []},
	"zdelay": {"names": ["zdelay"], "aliases": []},
	"zzfx": {"names": ["zzfx"], "aliases": []},
	"color": {"names": ["color", "colour"], "aliases": []},
	"midichan": {"names": ["midichan"], "aliases": []},
	"midimap": {"names": ["midimap"], "aliases": []},
	"midiport": {"names": ["midiport"], "aliases": []},
	"midicmd": {"names": ["midicmd"], "aliases": []},
	"ccn": {"names": ["ccn"], "aliases": []},
	"ccv": {"names": ["ccv"], "aliases": []},
	"ctlNum": {"names": ["ctlNum"], "aliases": []},
	"nrpnn": {"names": ["nrpnn"], "aliases": []},
	"nrpv": {"names": ["nrpv"], "aliases": []},
	"progNum": {"names": ["progNum"], "aliases": []},
	"sysexid": {"names": ["sysexid"], "aliases": []},
	"sysexdata": {"names": ["sysexdata"], "aliases": []},
	"midibend": {"names": ["midibend"], "aliases": []},
	"miditouch": {"names": ["miditouch"], "aliases": []},
	"polyTouch": {"names": ["polyTouch"], "aliases": []},
	"oschost": {"names": ["oschost"], "aliases": []},
	"oscport": {"names": ["oscport"], "aliases": []},
	"transient": {"names": ["transient", "transsustain"], "aliases": []},
	"FXrelease": {"names": ["FXrelease"], "aliases": ["FXrel", "FXr", "fxr"]},
	"fmh": {"names": ["fmh", "fmi"], "aliases": ["fmh", "fmh1", "fmh1", "fmi1"]},
	"fmh2": {"names": ["fmh2", "fmi2"], "aliases": ["fmh2"]},
	"fmh3": {"names": ["fmh3", "fmi3"], "aliases": ["fmh3"]},
	"fmh4": {"names": ["fmh4", "fmi4"], "aliases": ["fmh4"]},
	"fmh5": {"names": ["fmh5", "fmi5"], "aliases": ["fmh5"]},
	"fmh6": {"names": ["fmh6", "fmi6"], "aliases": ["fmh6"]},
	"fmh7": {"names": ["fmh7", "fmi7"], "aliases": ["fmh7"]},
	"fmh8": {"names": ["fmh8", "fmi8"], "aliases": ["fmh8"]},
	"fmi": {"names": ["fmi", "fmh"], "aliases": ["fm", "fm1", "fmi1", "fmh1"]},
	"fmi2": {"names": ["fmi2", "fmh2"], "aliases": ["fm2"]},
	"fmi3": {"names": ["fmi3", "fmh3"], "aliases": ["fm3"]},
	"fmi4": {"names": ["fmi4", "fmh4"], "aliases": ["fm4"]},
	"fmi5": {"names": ["fmi5", "fmh5"], "aliases": ["fm5"]},
	"fmi6": {"names": ["fmi6", "fmh6"], "aliases": ["fm6"]},
	"fmi7": {"names": ["fmi7", "fmh7"], "aliases": ["fm7"]},
	"fmi8": {"names": ["fmi8", "fmh8"], "aliases": ["fm8"]},
	"fmenv": {"names": ["fmenv"], "aliases": ["fme", "fme1", "fmenv1"]},
	"fmenv2": {"names": ["fmenv2"], "aliases": ["fme2"]},
	"fmenv3": {"names": ["fmenv3"], "aliases": ["fme3"]},
	"fmenv4": {"names": ["fmenv4"], "aliases": ["fme4"]},
	"fmenv5": {"names": ["fmenv5"], "aliases": ["fme5"]},
	"fmenv6": {"names": ["fmenv6"], "aliases": ["fme6"]},
	"fmenv7": {"names": ["fmenv7"], "aliases": ["fme7"]},
	"fmenv8": {"names": ["fmenv8"], "aliases": ["fme8"]},
	"fmattack": {"names": ["fmattack"], "aliases": ["fmatt", "fmatt1", "fmattack1"]},
	"fmattack2": {"names": ["fmattack2"], "aliases": ["fmatt2"]},
	"fmattack3": {"names": ["fmattack3"], "aliases": ["fmatt3"]},
	"fmattack4": {"names": ["fmattack4"], "aliases": ["fmatt4"]},
	"fmattack5": {"names": ["fmattack5"], "aliases": ["fmatt5"]},
	"fmattack6": {"names": ["fmattack6"], "aliases": ["fmatt6"]},
	"fmattack7": {"names": ["fmattack7"], "aliases": ["fmatt7"]},
	"fmattack8": {"names": ["fmattack8"], "aliases": ["fmatt8"]},
	"fmwave": {"names": ["fmwave"], "aliases": ["fmwave1"]},
	"fmwave2": {"names": ["fmwave2"], "aliases": []},
	"fmwave3": {"names": ["fmwave3"], "aliases": []},
	"fmwave4": {"names": ["fmwave4"], "aliases": []},
	"fmwave5": {"names": ["fmwave5"], "aliases": []},
	"fmwave6": {"names": ["fmwave6"], "aliases": []},
	"fmwave7": {"names": ["fmwave7"], "aliases": []},
	"fmwave8": {"names": ["fmwave8"], "aliases": []},
	"fmdecay": {"names": ["fmdecay"], "aliases": ["fmdec", "fmdec1", "fmdecay1"]},
	"fmdecay2": {"names": ["fmdecay2"], "aliases": ["fmdec2"]},
	"fmdecay3": {"names": ["fmdecay3"], "aliases": ["fmdec3"]},
	"fmdecay4": {"names": ["fmdecay4"], "aliases": ["fmdec4"]},
	"fmdecay5": {"names": ["fmdecay5"], "aliases": ["fmdec5"]},
	"fmdecay6": {"names": ["fmdecay6"], "aliases": ["fmdec6"]},
	"fmdecay7": {"names": ["fmdecay7"], "aliases": ["fmdec7"]},
	"fmdecay8": {"names": ["fmdecay8"], "aliases": ["fmdec8"]},
	"fmsustain": {"names": ["fmsustain"], "aliases": ["fmsus", "fmsus1", "fmsustain1"]},
	"fmsustain2": {"names": ["fmsustain2"], "aliases": ["fmsus2"]},
	"fmsustain3": {"names": ["fmsustain3"], "aliases": ["fmsus3"]},
	"fmsustain4": {"names": ["fmsustain4"], "aliases": ["fmsus4"]},
	"fmsustain5": {"names": ["fmsustain5"], "aliases": ["fmsus5"]},
	"fmsustain6": {"names": ["fmsustain6"], "aliases": ["fmsus6"]},
	"fmsustain7": {"names": ["fmsustain7"], "aliases": ["fmsus7"]},
	"fmsustain8": {"names": ["fmsustain8"], "aliases": ["fmsus8"]},
	"fmrelease": {"names": ["fmrelease"], "aliases": ["fmrel", "fmrel1", "fmrelease1"]},
	"fmrelease2": {"names": ["fmrelease2"], "aliases": ["fmrel2"]},
	"fmrelease3": {"names": ["fmrelease3"], "aliases": ["fmrel3"]},
	"fmrelease4": {"names": ["fmrelease4"], "aliases": ["fmrel4"]},
	"fmrelease5": {"names": ["fmrelease5"], "aliases": ["fmrel5"]},
	"fmrelease6": {"names": ["fmrelease6"], "aliases": ["fmrel6"]},
	"fmrelease7": {"names": ["fmrelease7"], "aliases": ["fmrel7"]},
	"fmrelease8": {"names": ["fmrelease8"], "aliases": ["fmrel8"]},
}


static func main_name(name: String) -> String:
	## Настоящее имя параметра по имени или псевдониму; "" — не параметр.
	if CONTROLS.has(name):
		return name
	return String(ALIASES.get(name, ""))


static func is_control(name: String) -> bool:
	return CONTROLS.has(name) or ALIASES.has(name)


const ALIASES := {
	"sound": "s",
	"wavetablePosition": "wt",
	"wtatt": "wtattack",
	"wtdec": "wtdecay",
	"wtsus": "wtsustain",
	"wtrel": "wtrelease",
	"wavetableWarp": "warp",
	"warpatt": "warpattack",
	"warpdec": "warpdecay",
	"warpsus": "warpsustain",
	"warprel": "warprelease",
	"wavetableWarpMode": "warpmode",
	"wavetablePhaseRand": "wtphaserand",
	"src": "source",
	"vel": "velocity",
	"att": "attack",
	"dec": "decay",
	"sus": "sustain",
	"rel": "release",
	"bpf": "bandf",
	"bp": "bandf",
	"bpq": "bandq",
	"loopb": "loopBegin",
	"loope": "loopEnd",
	"trem": "tremolo",
	"tremsync": "tremolosync",
	"tremdepth": "tremolodepth",
	"tremskew": "tremoloskew",
	"tremphase": "tremolophase",
	"tremshape": "tremoloshape",
	"duck": "duckorbit",
	"duckons": "duckonset",
	"duckatt": "duckattack",
	"datt": "duckattack",
	"bbexpr": "byteBeatExpression",
	"bb": "byteBeatExpression",
	"bbst": "byteBeatStartTime",
	"ch": "channels",
	"pwr": "pwrate",
	"pws": "pwsweep",
	"ph": "phaserrate",
	"phaser": "phaserrate",
	"phs": "phasersweep",
	"phc": "phasercenter",
	"phd": "phaserdepth",
	"phasdp": "phaserdepth",
	"ctf": "cutoff",
	"lpf": "cutoff",
	"lp": "cutoff",
	"lpe": "lpenv",
	"hpe": "hpenv",
	"bpe": "bpenv",
	"lpa": "lpattack",
	"hpa": "hpattack",
	"bpa": "bpattack",
	"lpd": "lpdecay",
	"hpd": "hpdecay",
	"bpd": "bpdecay",
	"lps": "lpsustain",
	"hps": "hpsustain",
	"bps": "bpsustain",
	"lpr": "lprelease",
	"hpr": "hprelease",
	"bpr": "bprelease",
	"lpdepthfreq": "lpdepthfrequency",
	"bpdepthfreq": "bpdepthfrequency",
	"hpdepthfreq": "hpdepthfrequency",
	"vibrato": "vib",
	"v": "vib",
	"vmod": "vibmod",
	"hpf": "hcutoff",
	"hp": "hcutoff",
	"hpq": "hresonance",
	"lpq": "resonance",
	"delayfb": "delayfeedback",
	"dfb": "delayfeedback",
	"delayt": "delaytime",
	"dt": "delaytime",
	"delays": "delaysync",
	"ds": "delaysync",
	"det": "detune",
	"fadeOutTime": "fadeTime",
	"patt": "pattack",
	"pdec": "pdecay",
	"psus": "psustain",
	"prel": "prelease",
	"gat": "gate",
	"oct": "octave",
	"o": "orbit",
	"bgain": "busgain",
	"dict": "dictionary",
	"rlp": "roomlp",
	"rdim": "roomdim",
	"rfade": "roomfade",
	"iresponse": "ir",
	"size": "roomsize",
	"sz": "roomsize",
	"rsize": "roomsize",
	"dist": "distort",
	"distvol": "distortvol",
	"disttype": "distorttype",
	"legato": "clip",
	"dur": "duration",
	"FXrel": "FXrelease",
	"FXr": "FXrelease",
	"fxr": "FXrelease",
	"fmh1": "fmh",
	"fmi1": "fmh",
	"fm": "fmi",
	"fm1": "fmi",
	"fm2": "fmi2",
	"fm3": "fmi3",
	"fm4": "fmi4",
	"fm5": "fmi5",
	"fm6": "fmi6",
	"fm7": "fmi7",
	"fm8": "fmi8",
	"fme": "fmenv",
	"fme1": "fmenv",
	"fmenv1": "fmenv",
	"fme2": "fmenv2",
	"fme3": "fmenv3",
	"fme4": "fmenv4",
	"fme5": "fmenv5",
	"fme6": "fmenv6",
	"fme7": "fmenv7",
	"fme8": "fmenv8",
	"fmatt": "fmattack",
	"fmatt1": "fmattack",
	"fmattack1": "fmattack",
	"fmatt2": "fmattack2",
	"fmatt3": "fmattack3",
	"fmatt4": "fmattack4",
	"fmatt5": "fmattack5",
	"fmatt6": "fmattack6",
	"fmatt7": "fmattack7",
	"fmatt8": "fmattack8",
	"fmwave1": "fmwave",
	"fmdec": "fmdecay",
	"fmdec1": "fmdecay",
	"fmdecay1": "fmdecay",
	"fmdec2": "fmdecay2",
	"fmdec3": "fmdecay3",
	"fmdec4": "fmdecay4",
	"fmdec5": "fmdecay5",
	"fmdec6": "fmdecay6",
	"fmdec7": "fmdecay7",
	"fmdec8": "fmdecay8",
	"fmsus": "fmsustain",
	"fmsus1": "fmsustain",
	"fmsustain1": "fmsustain",
	"fmsus2": "fmsustain2",
	"fmsus3": "fmsustain3",
	"fmsus4": "fmsustain4",
	"fmsus5": "fmsustain5",
	"fmsus6": "fmsustain6",
	"fmsus7": "fmsustain7",
	"fmsus8": "fmsustain8",
	"fmrel": "fmrelease",
	"fmrel1": "fmrelease",
	"fmrelease1": "fmrelease",
	"fmrel2": "fmrelease2",
	"fmrel3": "fmrelease3",
	"fmrel4": "fmrelease4",
	"fmrel5": "fmrelease5",
	"fmrel6": "fmrelease6",
	"fmrel7": "fmrelease7",
	"fmrel8": "fmrelease8",
}
